branches:
  only:
    - master
    - scala-2.9
    - scala-2.10
language: scala
jdk:
  - openjdk6
scala:
  - 2.11.5
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
install:
  # PATH and JAVA_HOME must be set here (not env:global:) or Travis overwrites
  - export JAVA_HOME=$HOME/jdk-6-oracle-x64
  - export PATH=$JAVA_HOME/bin:$PATH
  - hash -r
  - wget https://www.dropbox.com/s/uhbz9f712f2qhdw/oracle-java6-jdk_6u45_amd64.deb
  - ar p oracle-java6-jdk_6u45_amd64.deb data.tar.xz | tar Jx
  - mv usr/lib/jvm/jdk-6-oracle-x64 $JAVA_HOME
  - java -version
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test:compile doc && ./.check-diff.sh && sbt ++$TRAVIS_SCALA_VERSION test && sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
  - sbt ++$TRAVIS_SCALA_VERSION clean $(if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then echo "publish"; fi)
env:
  global:
    # travis encrypt -r ensime/ensime-server SONATYPE_USERNAME=<USERNAME>
    # travis encrypt -r ensime/ensime-server SONATYPE_PASSWORD=<PASSWORD>
    - secure: "IqDHZwYDAdif+BAJ0u57Ci7UEp4k0y8D+uDh51g6FqAIybD1HZ6TINojwj79675mjFaA9szXARkGAEuPfQ57tpC8Bevaj0zKX64TBE3HEdzuQL3i7dxi13DFEmCsUFeS7zqSMsqFcz5a6yASRujttDt2x0GCakOp82TvgI4NANM="
    - secure: "R90/HAOWcNEcs7CLx0ID/qLKBS9EC8Z52c9EPsmIx7dTWXGAOmbj7klUbWjkMsa/SkDYrfBTSPPsdW2QBY66pU8NeqL2YiguKNTVrOoFclEj/kfejQqJcII1PwwSBhVBXhp+bQ+ZHHe8MySDehK7hedL1fNzc8+RpLSUe2ROd90="
